### ISSUE TITLE
dude you realize this is kinda illegal 

### ISSUE THREAD

**Issue by ItsJustLag** [FOSS-Devs/freediscord#2]
hey there buddy chum pal friend buddy pal chum bud friend fella bruther amigo pal buddy friend chummy chum chum pal i don't mean to be rude my friend pal home slice bread slice dawg but i gotta warn ya if u don't take this one down i'm going to have to diddly darn report ya and wowza wouldn't that be a crummy juncture, huh? do yuo want that? do wish upon yourself to come into legal experience with a crummy juncture? because friend buddy chum friend chum pally pal chum friend if you keep this up well gosh diddly darn i just might have to get not so friendly with u my friendly friend friend pal friend buddy chum pally friend chum buddy...

But in all seriousness, this is kind of illegal. Rebranding an open source project protected by a license and claiming that YOU have worked on it is NOT okay. That's like forking a Linux Distro and claiming that you made it! Please take this down right now or reoccurcat and me will have to do some more "extreme measures" which I think none of us want to do.

**Comment by SKBotNL** [comment]
"protected by a license" this is not true

**Comment by SKBotNL** [comment]
(this has all been fixed with some discussions)
